### ISSUE TITLE
Unable to get WelcomeToVR app to work in Bash for Windows 10

### ISSUE THREAD

**Issue by Carpetfizz** [facebook/react-360#28]
Hello,

I followed the getting started instructions on your [blog post](https://developer.oculus.com/blog/introducing-the-react-vr-pre-release/) and I get the following error when I run `npm start` and `sudo npm start`.

Not sure if it matters, but I'm using Bash for Windows 10 which is running Ubuntu 14.04 LTS.

Thanks for any assistance!

```

watch /mnt/c/Users/ajayr/Documents/Code/WelcomeToVR EPERM

npm ERR! Linux 3.4.0+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! WelcomeToVR@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the WelcomeToVR@0.0.1 start script 'node node_modules/react-native/local-cli/cli.js start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the WelcomeToVR package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/react-native/local-cli/cli.js start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs WelcomeToVR
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls WelcomeToVR
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/Users/ajayr/Documents/Code/WelcomeToVR/npm-debug.log
```

**Comment by mikearmstrong001** [comment]
@amberroy would you mind having a look at the bash workflow. Thank you

**Comment by amberroy** [comment]
I'm running a different setup: Git-Bash on Windows 10, and `npm start` works.

Unfortunately I don't have the hardware to repro your specific case.  General tips in this case would be deleting your `node_modules` and re-run `npm install` and see if there are any errors.  You can also check the `npm-debug.log`

**Comment by mikearmstrong001** [comment]
@Carpetfizz did you make progress ? could you include `/mnt/c/Users/ajayr/Documents/Code/WelcomeToVR/npm-debug.log`

**Comment by Carpetfizz** [comment]
Hello, sorry I went dark on this! I've been away from the computer this issue occurred on and I will update you as soon as I get back to it!

**Comment by Carpetfizz** [comment]
Sorry for the suuper late reply. Here's a paste of my debug log:

http://pastebin.com/ju8MyccV

**Comment by IXIS-Justin** [comment]
@amberroy why was this closed?

I am having the same issue.  

Here is what happens when I run npm start

```
Scanning 593 folders for symlinks in /mnt/c/Users/g/src/rvr/hi/node_modules (58ms)
 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.                                            │
 │                                                                            │
 │  Keep this packager running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own packager instance if you          │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   /mnt/c/Users/g/src/rvr/hi


watch /mnt/c/Users/g/src/rvr/hi EPERM


npm ERR! Linux 3.4.0+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! hi@0.0.1 start: `node -e "console.log('open browser at http:/localhost:8081/vr/\n\n');" && node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hi@0.0.1 start script 'node -e "console.log('open browser at http:/localhost:8081/vr/\n\n');" && node node_modules/react-native/local-cli/cli.js start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node -e "console.log('open browser at http:/localhost:8081/vr/\n\n');" && node node_modules/react-native/local-cli/cli.js start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hi
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/Users/g/src/rvr/hi/npm-debug.log

```

And here is npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle hi@0.0.1~prestart: hi@0.0.1
6 silly lifecycle hi@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle hi@0.0.1~start: hi@0.0.1
8 verbose lifecycle hi@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle hi@0.0.1~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/mnt/c/Users/g/src/rvr/hi/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle hi@0.0.1~start: CWD: /mnt/c/Users/g/src/rvr/hi
11 silly lifecycle hi@0.0.1~start: Args: [ '-c',
11 silly lifecycle   'node -e "console.log(\'open browser at http:/localhost:8081/vr/\\n\\n\');" && node node_modules/react-native/local-cli/cli.js start' ]
12 silly lifecycle hi@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle hi@0.0.1~start: Failed to exec start script
14 verbose stack Error: hi@0.0.1 start: `node -e "console.log('open browser at http:/localhost:8081/vr/\n\n');" && node node_modules/react-native/local-cli/cli.js start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid hi@0.0.1
16 verbose cwd /mnt/c/Users/g/src/rvr/hi
17 error Linux 3.4.0+
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v6.10.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error hi@0.0.1 start: `node -e "console.log('open browser at http:/localhost:8081/vr/\n\n');" && node node_modules/react-native/local-cli/cli.js start`
22 error Exit status 1
23 error Failed at the hi@0.0.1 start script 'node -e "console.log('open browser at http:/localhost:8081/vr/\n\n');" && node node_modules/react-native/local-cli/cli.js start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the hi package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node -e "console.log('open browser at http:/localhost:8081/vr/\n\n');" && node node_modules/react-native/local-cli/cli.js start
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs hi
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls hi
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by IXIS-Justin** [comment]
Note, if I just run

`node node_modules/react-native/local-cli/cli.js start`

Then it fails silently (just stops running)

**Comment by amberroy** [comment]
Thanks for reporting we'll take a look.

**Comment by IXIS-Justin** [comment]
Thanks @amberroy if you can't reproduce, let me know what I can share.  To be clear, this is using the linux subsystem (ubuntu on windows), not the git-bash which is pure windows if I understand correctly.

**Comment by darklilium** [comment]
Im having almost the same issue. I followed the instructions on the website, and when i run npm run start i got this:
![image](https://cloud.githubusercontent.com/assets/8507515/25153011/604c5954-2461-11e7-9d60-f3a62220519b.png)
And then in the browser: 
![image](https://cloud.githubusercontent.com/assets/8507515/25153034/78dfc96a-2461-11e7-959c-b48f4b1ea3c9.png)

**Comment by sirkitree** [comment]
Same issue here.

```
watch /mnt/c/Users/sirki/repos/first_rvr EPERM
Error: watch /mnt/c/Users/sirki/repos/first_rvr EPERM
    at exports._errnoException (util.js:1018:11)
    at FSWatcher.start (fs.js:1443:19)
    at Object.fs.watch (fs.js:1470:11)
    at NodeWatcher.watchdir (/mnt/c/Users/sirki/repos/first_rvr/node_modules/sane/src/node_watcher.js:144:20)
    at new NodeWatcher (/mnt/c/Users/sirki/repos/first_rvr/node_modules/sane/src/node_watcher.js:45:8)
    at createWatcher (/mnt/c/Users/sirki/repos/first_rvr/node_modules/jest-haste-map/build/index.js:536:23)
    at Array.map (native)
    at HasteMap._watch (/mnt/c/Users/sirki/repos/first_rvr/node_modules/jest-haste-map/build/index.js:654:44)
    at _buildPromise._buildFileMap.then.then.hasteMap (/mnt/c/Users/sirki/repos/first_rvr/node_modules/jest-haste-map/build/index.js:250:21)
error Command failed with exit code 1.
```

**Comment by twisterghost** [comment]
Is this related to the fact that file watching is not yet supported in Bash on Ubuntu on Windows?

Seems like the same error I've seen before, an EPERM on FSWatcher.start.

**Comment by yoieh** [comment]
Works fine in WSL with Ubuntu 16.04. You should really try to upgrade or reinstall WSL if you have the Creators Update Installed.

In WSL for upgrade
$ `do-release-upgrade`
or in CMD/Powershell
```
lxrun /uninstall /full
lxrun /install
```

[More about WSL in Creators Update](https://blogs.msdn.microsoft.com/commandline/2017/04/11/windows-10-creators-update-whats-new-in-bashwsl-windows-console/)

I cant get LAN access tho. But that probable a config some ware i have mist. I'm pretty new to node severs.
