### ISSUE TITLE
error when using node 9.4.0

### ISSUE THREAD

**Issue by luruke** [facebook/react-360#441]
When using node 9.4.0 on osx `10.13.3` the `yarn start|npm start` commands fails:
```
╭─luigiderosa@luigi-MBP ~/epic/crop-trust/croptrust.vault-tour.v1  ‹dev›
╰─$ nvm use node
Now using node v9.4.0 (npm v5.6.0)
╭─luigiderosa@luigi-MBP ~/epic/crop-trust/croptrust.vault-tour.v1  ‹dev›
╰─$ node -v
v9.4.0
╭─luigiderosa@luigi-MBP ~/epic/crop-trust/croptrust.vault-tour.v1  ‹dev›
╰─$ yarn start
yarn run v1.3.2
$ node -e "console.log('open browser at http://localhost:8081/vr/\n\n');" && node node_modules/react-native/local-cli/cli.js start
open browser at http://localhost:8081/vr/


 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.                                            │
 │                                                                            │
 │  Keep this packager running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own packager instance if you          │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   /Users/luigiderosa/epic/crop-trust/croptrust.vault-tour.v1


React packager ready.

Loading dependency graph...(node:20218) UnhandledPromiseRejectionWarning: Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/luigiderosa/epic/crop-trust/croptrust.vault-tour.v1/node_modules/sane/src/fsevents_watcher.js:41:11)
    at createWatcher (/Users/luigiderosa/epic/crop-trust/croptrust.vault-tour.v1/node_modules/metro-bundler/node_modules/jest-haste-map/build/index.js:590:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/luigiderosa/epic/crop-trust/croptrust.vault-tour.v1/node_modules/metro-bundler/node_modules/jest-haste-map/build/index.js:737:25)
    at _buildPromise._buildFileMap.then.then.hasteMap (/Users/luigiderosa/epic/crop-trust/croptrust.vault-tour.v1/node_modules/metro-bundler/node_modules/jest-haste-map/build/index.js:269:21)
    at <anonymous>
(node:20218) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20218) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Everything works as expected when using `8.4.0`.

**Comment by andrewimm** [comment]
This is a problem with the React Native packager, which is unfortunately code we don't own. It's possible they've fixed their internals and we will pick up the fix when we perform the dependency upgrade I'm actively working on. Otherwise, I will follow up with their team.

In the meantime, you can try installing watchman. It's the recommended experience for developers on Linux and Mac, and should prevent this. Let me know how that goes.

**Comment by luruke** [comment]
Thank you @andrewimm ,
I don't have any specific reasons to use `9.40` right now, I can easily use older node versions.

Just wanted to flag the bug, we can close the issue for me.

**Comment by nicholasostman** [comment]
@andrewimm  It seems that the React-native packager is expecting index.js within the /VR/ directory to run locally, while in order to bundle for a production deploy, React-vr is using it's bundle which is expecting index.vr.js at the root. Please see https://github.com/facebook/react-native/releases?after=v0.49.3 as I'd presume the solution for VR would follow suit for simplicity sake. Let me know if I'm missing something please!
