### ISSUE TITLE
Failing to start

### ISSUE THREAD

**Issue by pnkapadia6** [facebook/react-360#475]
**Bug:**
Failing to start the default app by `npm start`
Error on terminal:
```
2018-05-11T22:31:17,589: [4086272960] the permissions on /usr/local/Cellar/watchman/4.4.0/var/run/watchman/pnkapadia6-state allow others to write to it. Verify that you own the contents and then fix its permissions by running `chmod 0700 /usr/local/Cellar/watchman/4.4.0/var/run/watchman/pnkapadia6-state`

Watchman:  watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= 2018-05-11T22:31:17,589: [4086272960] the permissions on /usr/local/Cellar/watchman/4.4.0/var/run/watchman/pnkapadia6-state allow others to write to it. Verify that you own the contents and then fix its permissions by running `chmod 0700 /usr/local/Cellar/watchman/4.4.0/var/run/watchman/pnkapadia6-state`
Bundling `client.js`  [development, non-minified]  0.0% (0/1), failed.
Loading dependency graph...
Bundling `client.js`  [development, non-minified]  ░░░░░░░░░░░░░░░░  0.0% (0/1)Error: Failed to start watch mode.
    at Timeout.setTimeout (/Users/pnkapadia6/prash/vr/HelloReact360/node_modules/metro-bundler/node_modules/jest-haste-map/build/index.js:605:22)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
(node:88271) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to start watch mode.
(node:88271) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejectiLoading dependency graph...2018-05-11T22:32:17,609: [4086272960] the permissions on /usr/local/Cellar/watchman/4.4.0/var/run/watchman/pnkapadia6-state allow others to write to it. Verify that you own the contents and then fix its permissions by running `chmod 0700 /usr/local/Cellar/watchman/4.4.0/var/run/watchman/pnkapadia6-state`

Watchman:  watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= 2018-05-11T22:32:17,609: [4086272960] the permissions on /usr/local/Cellar/watchman/4.4.0/var/run/watchman/pnkapadia6-state allow others to write to it. Verify that you own the contents and then fix its permissions by running `chmod 0700 /usr/local/Cellar/watchman/4.4.0/var/run/watchman/pnkapadia6-state`
```

Error in browser:
`index.html:13 Uncaught ReferenceError: React360 is not defined`

* 'react-360' package version: 1.0.0
* 'react-360-web' package version: 1.0.0
* Operating System: MacOS
* Browser: Any
* Node version: v8.9.3
* Yarn version: 1.5.1

**Comment by pnkapadia6** [comment]
Nevermind. Had some issues with permissions. Fixed it. Thanks!

**Comment by PetarBegovic1701** [comment]
@pnkapadia6 how did you solve this?
Can you please post a solution?

**Comment by pnkapadia6** [comment]
@PetarBegovic1701 Are you getting a similar error on terminal? There was some issue with watchman permissions, had to run chmod for the same.

**Comment by PetarBegovic1701** [comment]
It was a combo of issues.
An older node version and #548.
Thanks for the quick reply @pnkapadia6

**Comment by KishokanthJeganathan** [comment]
@pnkapadia6 Im having this issue now :/

Metro Bundler ready.
```

Loading dependency graph...(node:13012) UnhandledPromiseRejectionWarning: Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/kishokanthjeganathan/Documents/Final-Code/Hello360/node_modules/sane/src/fsevents_watcher.js:41:11)
    at createWatcher (/Users/kishokanthjeganathan/Documents/Final-Code/Hello360/node_modules/jest-haste-map/build/index.js:572:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/kishokanthjeganathan/Documents/Final-Code/Hello360/node_modules/jest-haste-map/build/index.js:683:44)
    at /Users/kishokanthjeganathan/Documents/Final-Code/Hello360/node_modules/jest-haste-map/build/index.js:280:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:13012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13012) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
How did you solve it mate :/
