### ISSUE TITLE
`metro-bundler` not specified as devDependency

### ISSUE THREAD

**Issue by ryami333** [facebook/react-360#529]
### Description

When I used the `react-360-cli` tool to `init` a new app, then tried to `npm install` and `npm run start` then I got this error:
```
module.js:549
    throw err;
    ^

Error: Cannot find module 'metro-bundler/src/blacklist'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/to/project/rn-cli.config.js:4:17)
    at Module._compile (module.js:652:30)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .js] (/path/to/project/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
npm ERR! code ELIFECYCLE
```

#### Expected behavior

After I `npm install` then all of the dependencies should be encapsulated in `node_modules`.

#### Actual behavior

`npm run start` crashes, as above.

### Reproduction

```
npx react-360-cli init foo
cd foo
npm install
npm run start
```

### Solution

`package.json` needs to have a compatible version of `metro-bundler` in it's `devDependencies`.

**Comment by ryami333** [comment]
Ignore this sorry, PEBCAC issue!
