### ISSUE TITLE
Error: Cannot find module './clone.js'

### ISSUE THREAD

**Issue by droganov** [facebook/react-360#615]
### description

This is a Bug: when I ran `react-360 init app` it failed with:

````
error /Users/.../node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/.../node_modules/electron
Output:
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module './clone.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/se/www/node/moduli/node_modules/graceful-fs/graceful-fs.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
````

### Reproduction
It happened under Mac OS 10.13.6, I tried 2 versions of node 10.11.0 and 11.1.0

Both failed. Version manager is asdf, shell — fish

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* 'react-360' package version: [moduli@0.0.1 /Users/.../moduli
└── react-360@1.0.0 ]
* 'react-360-web' package version: [moduli@0.0.1 /Users/.../moduli
└── react-360-web@1.0.2 ]
* Operating System: [MacOS]

**Comment by larrylin28** [comment]
How did you run the `react-360 init app` command, is it from a shell command window or something else? The error log you put here shows error comes from `electron`, while react-360 cli has no dependencies on electron.
